import { getRequestHeaders } from "@tanstack/react-start/server"
import { createServerFn } from "@tanstack/react-start"
import { desc, eq } from "drizzle-orm"
import { APIError } from "better-auth/api"
import { waitUntil } from "cloudflare:workers"
import { auth } from "@/auth"
import { logManagementEvent } from "@/lib/analytics"
import { db } from "@/db"
import { oauthClient } from "@/schemas/auth"
import { AdminMiddleware } from "@/middleware"
import { assertOwnsApp } from "./assert-owns-app"
import {
    appIdSchema,
    createAppSchema,
    PENDING_REDIRECT_URI,
    setAppActiveSchema,
    updateAppSchema,
} from "./types"
import { forwardAuthHeaders } from "@/lib/forward-headers"

type OAuthClientRow = typeof oauthClient.$inferSelect

// schemas/auth.ts is generated by `auth:gen` (better-auth CLI), so we
// don't hand-edit its `metadata: text(..., { mode: "json" })` column.
// The oauth-provider plugin already JSON.stringifies metadata itself
// before handing it to the adapter (oauthToSchema/schemaToOAuth), and
// the "json" mode column stringifies again on top of that, so what
// Drizzle hands back here is a JSON string of a JSON string rather than
// a parsed object. Unwrap defensively (up to two passes) instead of
// touching the generated schema.
function parseFramework(metadata: unknown): string | null {
    let value = metadata
    for (let i = 0; i < 2 && typeof value === "string"; i++) {
        try {
            value = JSON.parse(value)
        } catch {
            return null
        }
    }
    if (value && typeof value === "object" && "framework" in value) {
        const framework = (value as { framework?: unknown })
            .framework
        return typeof framework === "string" ? framework : null
    }
    return null
}

function toAppDetail(row: OAuthClientRow, callerId: string) {
    return {
        id: row.id,
        clientId: row.clientId,
        name: row.name,
        uri: row.uri,
        icon: row.icon,
        applicationType: row.applicationType,
        disabled: row.disabled,
        redirectUris:
            (row.redirectUris as string[] | null) ?? [],
        postLogoutRedirectUris:
            (row.postLogoutRedirectUris as string[] | null) ??
            [],
        grantTypes: (row.grantTypes as string[] | null) ?? [],
        scopes: (row.scopes as string[] | null) ?? [],
        tokenEndpointAuthMethod: row.tokenEndpointAuthMethod,
        requirePKCE: row.requirePKCE,
        skipConsent: row.skipConsent,
        enableEndSession: row.enableEndSession,
        framework: parseFramework(row.metadata),
        isOwnClient:
            row.userId === null || row.userId === callerId,
        createdAt: row.createdAt,
        updatedAt: row.updatedAt,
    }
}

// getRequestHeaders() already returns a real Headers instance (h3's
// event.req.headers); Object.entries() only reads OWN enumerable
// properties, which a Headers object has none of, so
// Object.fromEntries(Object.entries(headers)) always produced {} here,
// silently dropping the session cookie on every admin oauth-client call
function headers() {
    return getRequestHeaders()
}

export type ListedApp = ReturnType<typeof toAppDetail>
function withClientMetadataError(error: unknown): never {
    if (error instanceof APIError && !error.message) {
        const description =
            error.body &&
                typeof error.body === "object" &&
                ("error_description" in error.body ||
                    "message" in error.body)
                ? String(
                    (error.body as Record<string, unknown>)
                        .message ??
                    (
                        error.body as Record<
                            string,
                            unknown
                        >
                    ).error_description
                )
                // the oauth-provider plugin throws several of its own
                // checks (assertClientPrivileges among them) as a bare
                // `new APIError(status)` with no body at all, which used
                // to surface as a silent, description-less toast
                : `${error.status} from the identity server, no further detail given`
        throw new APIError(error.status, { message: description })
    }
    throw error
}

const SECRET_CHARS =
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
function generateSecret(length: number): string {
    const bytes = new Uint8Array(length)
    crypto.getRandomValues(bytes)
    return Array.from(
        bytes,
        (b) => SECRET_CHARS[b % SECRET_CHARS.length]
    ).join("")
}

async function hashClientSecret(
    secret: string
): Promise<string> {
    const digest = await crypto.subtle.digest(
        "SHA-256",
        new TextEncoder().encode(secret)
    )
    let binary = ""
    for (const b of new Uint8Array(digest))
        binary += String.fromCharCode(b)
    return btoa(binary)
        .replace(/\+/g, "-")
        .replace(/\//g, "_")
        .replace(/=+$/, "")
}

export const listApps = createServerFn({ method: "GET" })
    .middleware([AdminMiddleware])
    .handler(async ({ context: { sessions } }) => {
        const rows = await db
            .select()
            .from(oauthClient)
            .orderBy(desc(oauthClient.createdAt))
        return {
            applications: rows.map((row) =>
                toAppDetail(row, sessions.user.id)
            ),
        }
    })

export type AppListData = Awaited<ReturnType<typeof listApps>>
export const findApp = createServerFn({ method: "GET" })
    .middleware([AdminMiddleware])
    .validator(appIdSchema)
    .handler(async ({ data, context: { sessions } }) => {
        const [row] = await db
            .select()
            .from(oauthClient)
            .where(eq(oauthClient.clientId, data.clientId))
        return row ? toAppDetail(row, sessions.user.id) : null
    })

export type AppDetail = Awaited<ReturnType<typeof findApp>>

export const createApp = createServerFn({ method: "POST" })
    .middleware([AdminMiddleware])
    .validator(createAppSchema)
    .handler(async ({ data }) => {
        try {
            const {
                headers: responseHeaders,
                response
            } = await auth.api.adminCreateOAuthClient({
                headers: headers(),
                body: {
                    client_name: data.client_name,
                    client_uri: data.client_uri,
                    logo_uri: data.logo_uri,
                    application_type:
                        data.application_type,
                    token_endpoint_auth_method:
                        data.token_endpoint_auth_method,
                    redirect_uris: data.redirect_uris
                        ?.length
                        ? data.redirect_uris
                        : [PENDING_REDIRECT_URI],
                    post_logout_redirect_uris:
                        data.post_logout_redirect_uris,
                    scope: data.scope.join(" "),
                    grant_types: data.grant_types,
                    require_pkce: data.require_pkce,
                    skip_consent: data.skip_consent,
                    enable_end_session:
                        data.enable_end_session,
                    ...(data.framework && {
                        metadata: {
                            framework: data.framework,
                        },
                    }),
                },
                returnHeaders: true
            })
            forwardAuthHeaders(responseHeaders)
            return {
                clientId: response.client_id,
                clientSecret: response.client_secret ?? null,
            }
        } catch (error) {
            withClientMetadataError(error)
        }
    })

export type CreatedApp = Awaited<ReturnType<typeof createApp>>

export const updateApp = createServerFn({ method: "POST" })
    .middleware([AdminMiddleware])
    .validator(updateAppSchema)
    .handler(async ({ data }): Promise<{ success: true }> => {
        const { clientId, scope, framework, ...rest } = data
        try {
            await auth.api.adminUpdateOAuthClient({
                headers: headers(),
                body: {
                    client_id: clientId,
                    update: {
                        ...rest,
                        ...(scope && {
                            scope: scope.join(" "),
                        }),
                        ...(framework && {
                            metadata: { framework },
                        }),
                    },
                },
                returnHeaders: true
            })
            return { success: true }
        } catch (error) {
            withClientMetadataError(error)
        }
    })

export const setAppActive = createServerFn({ method: "POST" })
    .middleware([AdminMiddleware])
    .validator(setAppActiveSchema)
    .handler(
        async ({
            data,
            context: { sessions },
        }): Promise<{ success: true }> => {
            await db
                .update(oauthClient)
                .set({ disabled: !data.active })
                .where(
                    eq(oauthClient.clientId, data.clientId)
                )
            waitUntil(
                logManagementEvent({
                    action: data.active
                        ? "console.enable-app"
                        : "console.disable-app",
                    actorId: sessions.user.id,
                    targetId: data.clientId,
                })
            )
            return { success: true }
        }
    )

export const rotateApp = createServerFn({ method: "POST" })
    .middleware([AdminMiddleware])
    .validator(appIdSchema)
    .handler(
        async ({
            data,
            context: { sessions },
        }): Promise<{ clientSecret: string | null }> => {
            const [client] = await db
                .select({
                    clientSecret: oauthClient.clientSecret,
                    tokenEndpointAuthMethod:
                        oauthClient.tokenEndpointAuthMethod,
                    userId: oauthClient.userId,
                })
                .from(oauthClient)
                .where(
                    eq(oauthClient.clientId, data.clientId)
                )
            if (!client) {
                throw new Error("Application not found")
            }
            assertOwnsApp(
                client.userId,
                sessions.user.id,
                "rotate its secret"
            )
            if (
                !client.clientSecret ||
                client.tokenEndpointAuthMethod === "none"
            ) {
                throw new Error(
                    "Public clients cannot be rotated"
                )
            }
            const clientSecret = generateSecret(32)
            await db
                .update(oauthClient)
                .set({
                    clientSecret:
                        await hashClientSecret(clientSecret),
                    updatedAt: new Date(),
                })
                .where(
                    eq(oauthClient.clientId, data.clientId)
                )
            waitUntil(
                logManagementEvent({
                    action: "console.rotate-app",
                    actorId: sessions.user.id,
                    targetId: data.clientId,
                })
            )
            return { clientSecret }
        }
    )

export const removeApp = createServerFn({ method: "POST" })
    .middleware([AdminMiddleware])
    .validator(appIdSchema)
    .handler(
        async ({
            data,
            context: { sessions },
        }): Promise<{ success: true }> => {
            const [client] = await db
                .select({ userId: oauthClient.userId })
                .from(oauthClient)
                .where(
                    eq(oauthClient.clientId, data.clientId)
                )
            if (!client) {
                throw new Error("Application not found")
            }
            assertOwnsApp(
                client.userId,
                sessions.user.id,
                "remove it"
            )
            await db
                .delete(oauthClient)
                .where(
                    eq(oauthClient.clientId, data.clientId)
                )
            waitUntil(
                logManagementEvent({
                    action: "console.remove-app",
                    actorId: sessions.user.id,
                    targetId: data.clientId,
                })
            )
            return { success: true }
        }
    )
