-- better-auth 1.6.29 -> 1.7.1 schema migration, hand-written because
-- getMigrations()/runMigrations() cannot run against D1 on this version:
-- its new index-diff step joins sqlite_master with pragma_index_list()/
-- pragma_index_info() as table-valued functions, which D1's SQL authorizer
-- rejects with SQLITE_AUTH (confirmed directly against D1's own query API,
-- independent of better-auth). The DDL below was generated by running the
-- real getMigrations()/runMigrations() against a throwaway plain SQLite
-- file with the same plugin config, then diffed against this database's
-- actual pre-migration schema, since a fresh scratch DB can't produce
-- ALTER-style diffs for tables that already have rows.
--
-- Run with: wrangler d1 execute AUTH_DB --local  --file=migrations/0001_better_auth_1.7.sql
--       or: wrangler d1 execute AUTH_DB --remote --file=migrations/0001_better_auth_1.7.sql

-- new oauth-provider tables (resource model, RFC 8707 fix)
CREATE TABLE "oauthResource" (
    "id" text not null primary key,
    "identifier" text not null unique,
    "name" text not null,
    "accessTokenTtl" integer,
    "refreshTokenTtl" integer,
    "signingAlgorithm" text,
    "signingKeyId" text,
    "allowedScopes" text,
    "customClaims" text,
    "dpopBoundAccessTokensRequired" integer,
    "disabled" integer,
    "createdAt" date,
    "updatedAt" date,
    "policyVersion" integer,
    "metadata" text
);

CREATE TABLE "oauthClientAssertion" (
    "id" text not null primary key,
    "expiresAt" date not null
);

CREATE TABLE "oauthClientResource" (
    "id" text not null primary key,
    "clientId" text not null references "oauthClient" ("clientId") on delete cascade,
    "resourceId" text not null references "oauthResource" ("identifier") on delete cascade,
    "metadata" text,
    "createdAt" date
);
CREATE INDEX "oauthClientResource_clientId_idx" on "oauthClientResource" ("clientId");
CREATE UNIQUE INDEX "oauthClientResource_clientId_resourceId_uidx" on "oauthClientResource" ("clientId", "resourceId");
CREATE INDEX "oauthClientResource_resourceId_idx" on "oauthClientResource" ("resourceId");

-- account: add issuer, scoped identity by (issuer, accountId).
-- Rebuilt (not ALTER) so issuer can be NOT NULL, matching better-auth's
-- own schema exactly -- SQLite can't add a NOT NULL column to a populated
-- table in place. Every existing row here is a "credential" (email/password)
-- account -- this app has no social sign-in providers configured -- so the
-- backfill is exactly better-auth's own createLocalAccountIssuer("credential").
-- If a social provider is ever added before this runs elsewhere, extend the
-- CASE below for its providerId before applying.
CREATE TABLE "account_new" (
    "id" text not null primary key,
    "issuer" text not null,
    "accountId" text not null,
    "providerId" text not null,
    "userId" text not null references "user" ("id") on delete cascade,
    "accessToken" text,
    "refreshToken" text,
    "idToken" text,
    "accessTokenExpiresAt" date,
    "refreshTokenExpiresAt" date,
    "scope" text,
    "password" text,
    "createdAt" date not null,
    "updatedAt" date not null
);
INSERT INTO "account_new" (
    "id", "issuer", "accountId", "providerId", "userId", "accessToken",
    "refreshToken", "idToken", "accessTokenExpiresAt", "refreshTokenExpiresAt",
    "scope", "password", "createdAt", "updatedAt"
)
SELECT
    "id",
    CASE "providerId" WHEN 'credential' THEN 'local:credential' ELSE 'local:' || "providerId" END,
    "accountId", "providerId", "userId", "accessToken",
    "refreshToken", "idToken", "accessTokenExpiresAt", "refreshTokenExpiresAt",
    "scope", "password", "createdAt", "updatedAt"
FROM "account";
DROP TABLE "account";
ALTER TABLE "account_new" RENAME TO "account";
CREATE UNIQUE INDEX "account_issuer_accountId_uidx" on "account" ("issuer", "accountId");
CREATE INDEX "account_userId_idx" on "account" ("userId");

-- oauthClient: type/public -> applicationType (aligned with MCP authorization
-- client metadata, #10577). This app's console previously offered a third
-- "user-agent-based" client type; better-auth 1.7 only models "web"/"native",
-- so it collapses in here the same way the app code now does: anything that
-- isn't "web" is a public, no-secret client either way, so it becomes "native".
CREATE TABLE "oauthClient_new" (
    "id" text not null primary key,
    "clientId" text not null unique,
    "clientSecret" text,
    "clientDiscoveryId" text,
    "disabled" integer,
    "skipConsent" integer,
    "enableEndSession" integer,
    "subjectType" text,
    "scopes" text,
    "clientCredentialsScopes" text,
    "userId" text references "user" ("id") on delete cascade,
    "createdAt" date,
    "updatedAt" date,
    "name" text,
    "uri" text,
    "icon" text,
    "contacts" text,
    "tos" text,
    "policy" text,
    "softwareId" text,
    "softwareVersion" text,
    "softwareStatement" text,
    "redirectUris" text not null,
    "postLogoutRedirectUris" text,
    "backchannelLogoutUri" text,
    "backchannelLogoutSessionRequired" integer,
    "tokenEndpointAuthMethod" text,
    "applicationType" text,
    "jwks" text,
    "jwksUri" text,
    "grantTypes" text,
    "responseTypes" text,
    "requirePKCE" integer,
    "dpopBoundAccessTokens" integer,
    "referenceId" text,
    "metadata" text
);
INSERT INTO "oauthClient_new" (
    "id", "clientId", "clientSecret", "disabled", "skipConsent", "enableEndSession",
    "subjectType", "scopes", "userId", "createdAt", "updatedAt", "name", "uri", "icon",
    "contacts", "tos", "policy", "softwareId", "softwareVersion", "softwareStatement",
    "redirectUris", "postLogoutRedirectUris", "tokenEndpointAuthMethod", "applicationType",
    "grantTypes", "responseTypes", "requirePKCE", "referenceId", "metadata"
)
SELECT
    "id", "clientId", "clientSecret", "disabled", "skipConsent", "enableEndSession",
    "subjectType", "scopes", "userId", "createdAt", "updatedAt", "name", "uri", "icon",
    "contacts", "tos", "policy", "softwareId", "softwareVersion", "softwareStatement",
    "redirectUris", "postLogoutRedirectUris", "tokenEndpointAuthMethod",
    CASE "type" WHEN 'web' THEN 'web' ELSE 'native' END,
    "grantTypes", "responseTypes", "requirePKCE", "referenceId", "metadata"
FROM "oauthClient";
DROP TABLE "oauthClient";
ALTER TABLE "oauthClient_new" RENAME TO "oauthClient";
CREATE INDEX "oauthClient_userId_idx" on "oauthClient" ("userId");

-- oauthAccessToken / oauthRefreshToken / oauthConsent: purely additive,
-- nullable columns for the new resource-binding model -- no rebuild needed
ALTER TABLE "oauthAccessToken" ADD COLUMN "authorizationCodeId" text;
ALTER TABLE "oauthAccessToken" ADD COLUMN "resources" text;
ALTER TABLE "oauthAccessToken" ADD COLUMN "requestedUserInfoClaims" text;
ALTER TABLE "oauthAccessToken" ADD COLUMN "revoked" date;
ALTER TABLE "oauthAccessToken" ADD COLUMN "confirmation" text;
CREATE INDEX "oauthAccessToken_authorizationCodeId_idx" on "oauthAccessToken" ("authorizationCodeId");

ALTER TABLE "oauthRefreshToken" ADD COLUMN "authorizationCodeId" text;
ALTER TABLE "oauthRefreshToken" ADD COLUMN "resources" text;
ALTER TABLE "oauthRefreshToken" ADD COLUMN "requestedUserInfoClaims" text;
ALTER TABLE "oauthRefreshToken" ADD COLUMN "rotatedAt" date;
ALTER TABLE "oauthRefreshToken" ADD COLUMN "rotationReplayResponse" text;
ALTER TABLE "oauthRefreshToken" ADD COLUMN "rotationReplayExpiresAt" date;
ALTER TABLE "oauthRefreshToken" ADD COLUMN "confirmation" text;
CREATE INDEX "oauthRefreshToken_authorizationCodeId_idx" on "oauthRefreshToken" ("authorizationCodeId");

ALTER TABLE "oauthConsent" ADD COLUMN "resources" text;
ALTER TABLE "oauthConsent" ADD COLUMN "requestedUserInfoClaims" text;
