/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as AuthSetupRouteImport } from './routes/_auth/setup'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ProtectedUnauthorizedRouteImport } from './routes/_protected/unauthorized'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace/index'
import { Route as WorkspaceApiKeysRouteImport } from './routes/_workspace/api-keys'
import { Route as WorkspaceProvidersRouteImport } from './routes/_workspace/providers'
import { Route as WorkspaceTeamRolesRouteImport } from './routes/_workspace/team-roles'
import { Route as WorkspaceUsersRouteImport } from './routes/_workspace/users'
import { Route as ApiMigrateRouteImport } from './routes/api/migrate'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedUnauthorizedRoute = ProtectedUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceApiKeysRoute = WorkspaceApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceProvidersRoute = WorkspaceProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceTeamRolesRoute = WorkspaceTeamRolesRouteImport.update({
  id: '/team-roles',
  path: '/team-roles',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceUsersRoute = WorkspaceUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const ApiMigrateRoute = ApiMigrateRouteImport.update({
  id: '/api/migrate',
  path: '/api/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/setup': typeof AuthSetupRoute
  '/sign-in': typeof AuthSignInRoute
  '/unauthorized': typeof ProtectedUnauthorizedRoute
  '/api-keys': typeof WorkspaceApiKeysRoute
  '/providers': typeof WorkspaceProvidersRoute
  '/team-roles': typeof WorkspaceTeamRolesRoute
  '/users': typeof WorkspaceUsersRoute
  '/api/migrate': typeof ApiMigrateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkspaceIndexRoute
  '/setup': typeof AuthSetupRoute
  '/sign-in': typeof AuthSignInRoute
  '/unauthorized': typeof ProtectedUnauthorizedRoute
  '/api-keys': typeof WorkspaceApiKeysRoute
  '/providers': typeof WorkspaceProvidersRoute
  '/team-roles': typeof WorkspaceTeamRolesRoute
  '/users': typeof WorkspaceUsersRoute
  '/api/migrate': typeof ApiMigrateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/_auth/setup': typeof AuthSetupRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_protected/unauthorized': typeof ProtectedUnauthorizedRoute
  '/_workspace/api-keys': typeof WorkspaceApiKeysRoute
  '/_workspace/providers': typeof WorkspaceProvidersRoute
  '/_workspace/team-roles': typeof WorkspaceTeamRolesRoute
  '/_workspace/users': typeof WorkspaceUsersRoute
  '/api/migrate': typeof ApiMigrateRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/sign-in'
    | '/unauthorized'
    | '/api-keys'
    | '/providers'
    | '/team-roles'
    | '/users'
    | '/api/migrate'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/sign-in'
    | '/unauthorized'
    | '/api-keys'
    | '/providers'
    | '/team-roles'
    | '/users'
    | '/api/migrate'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_workspace'
    | '/_auth/setup'
    | '/_auth/sign-in'
    | '/_protected/unauthorized'
    | '/_workspace/api-keys'
    | '/_workspace/providers'
    | '/_workspace/team-roles'
    | '/_workspace/users'
    | '/api/migrate'
    | '/_workspace/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  ApiMigrateRoute: typeof ApiMigrateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/unauthorized': {
      id: '/_protected/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof ProtectedUnauthorizedRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/api-keys': {
      id: '/_workspace/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof WorkspaceApiKeysRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/providers': {
      id: '/_workspace/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof WorkspaceProvidersRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/team-roles': {
      id: '/_workspace/team-roles'
      path: '/team-roles'
      fullPath: '/team-roles'
      preLoaderRoute: typeof WorkspaceTeamRolesRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/users': {
      id: '/_workspace/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof WorkspaceUsersRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/api/migrate': {
      id: '/api/migrate'
      path: '/api/migrate'
      fullPath: '/api/migrate'
      preLoaderRoute: typeof ApiMigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSetupRoute: typeof AuthSetupRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSetupRoute: AuthSetupRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedUnauthorizedRoute: typeof ProtectedUnauthorizedRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedUnauthorizedRoute: ProtectedUnauthorizedRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface WorkspaceRouteRouteChildren {
  WorkspaceApiKeysRoute: typeof WorkspaceApiKeysRoute
  WorkspaceProvidersRoute: typeof WorkspaceProvidersRoute
  WorkspaceTeamRolesRoute: typeof WorkspaceTeamRolesRoute
  WorkspaceUsersRoute: typeof WorkspaceUsersRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceApiKeysRoute: WorkspaceApiKeysRoute,
  WorkspaceProvidersRoute: WorkspaceProvidersRoute,
  WorkspaceTeamRolesRoute: WorkspaceTeamRolesRoute,
  WorkspaceUsersRoute: WorkspaceUsersRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  ApiMigrateRoute: ApiMigrateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
